create database edoctor;
use edoctor;
   /* This Stores Doctors INFORMATION*/
   CREATE TABLE  DOCTOR 
   (    ID INTEGER AUTO_INCREMENT,
   FIRST_NAME VARCHAR(30), 
    LAST_NAME VARCHAR(30), 
    GENDER VARCHAR(8), 
    DATE_OF_BIRTH DATE, 
    EMAIL VARCHAR(100), 
    PHONE_NO VARCHAR(20),
    SPECIALTY VARCHAR(50), 
    TYPE VARCHAR(20), 
    NAME VARCHAR(60) NOT NULL , 
    PASSWORD VARCHAR(200) NOT NULL ,
     PRIMARY KEY (ID) 
	 
   );
   
      /* This Stores Receptionist INFORMATION*/
   CREATE TABLE  RECEPTIONIST 
   (    ID INTEGER AUTO_INCREMENT, 
	FIRST_NAME VARCHAR(30), 
    LAST_NAME VARCHAR(30), 
    GENDER VARCHAR(8), 
    DATE_OF_BIRTH DATE, 
    EMAIL VARCHAR(100), 
    PHONE_NO VARCHAR(20), 
    SALARY DOUBLE,
    USER_NAME VARCHAR(60) NOT NULL, 
    PASSWORD VARCHAR(200) NOT NULL ,
    DISCHARGED BOOLEAN,
     PRIMARY KEY (ID)
   );
   
      /* This Stores Patients INFORMATION*/
   CREATE TABLE  PATIENT 
   (    ID INTEGER AUTO_INCREMENT, 
    FIRST_NAME VARCHAR(30), 
    LAST_NAME VARCHAR(30), 
    GENDER VARCHAR(8), 
    DATE_OF_BIRTH DATE, 
    EMAIL VARCHAR(100), 
    ADDRESS VARCHAR(100), 
    PHONE_NO VARCHAR(20), 
    INFO VARCHAR(1000),
    USER_NAME VARCHAR(60) NOT NULL UNIQUE , 
    PASSWORD VARCHAR(200) NOT NULL ,
     PRIMARY KEY (ID) 
   );

      /* This Stores Appointments INFORMATION*/
   CREATE TABLE APPOINTMENT (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  PATIENT_ID INTEGER DEFAULT NULL,
  foreign key (PATIENT_ID) references PATIENT(id),
  DOCTOR_ID INTEGER DEFAULT NULL,
  foreign key (DOCTOR_ID) references DOCTOR(id),
  DATE_OF_APPOINTMENT date DEFAULT NULL
);
   
      /* This Stores Patient prescriptions INFORMATION*/
   CREATE TABLE  PRESCRIPTION 
   (    ID INTEGER AUTO_INCREMENT, 
    DOSAGE VARCHAR(100), 
    DETAILS VARCHAR(2000), 
    FROM_DATE DATE, 
    TO_DATE DATE,
     PRIMARY KEY (ID) 
   ) ;
   
      /* This Stores patient session INFORMATION*/
   CREATE TABLE  PATIENT_SESSION 
   (    ID INTEGER AUTO_INCREMENT, 
    APPOINTMENT_ID INTEGER , 
    foreign key (appointment_id) references APPOINTMENT(id),
    DURATION time, 
    PRESCRIPTION INTEGER ,
    foreign key (prescription) references PRESCRIPTION(id),
     COST DOUBLE NOT NULL,
     DESCRIPTION VARCHAR(1500),
     PRIMARY KEY (ID)
   );

   
      /* This Stores temporary/requested/pending patient appointments INFORMATION*/
   
   CREATE TABLE  REQUESTED_APPOINTMENT 
   (    ID INTEGER AUTO_INCREMENT, 
    PATIENT_ID INTEGER NOT NULL , 
    DOCTOR_ID INTEGER NOT NULL , 
    DATE_OF_APPOINTMENT DATE NOT NULL ,
    STATUS BOOLEAN, 
     PRIMARY KEY (ID) , 
     UNIQUE (PATIENT_ID, DOCTOR_ID, DATE_OF_APPOINTMENT) 
   ) ;

    /* This Stores  (Problems/Illneses) with each assigned to a doctor type INFORMATION [TEST] */ 
    CREATE TABLE ILLNESES
    (ID INTEGER AUTO_INCREMENT,
     NAME VARCHAR(100) NOT NULL,
     DESCRIPTION VARCHAR(100),
     DOCTOR_TYPE VARCHAR(20) NOT NULL,
     CLEANIMG LONGBLOB NOT NULL,
     EFFECTIMG LONGBLOB NOT NULL,
     PRIMARY KEY(ID)

    );

    /* This Stores  Cases  with each assigned to a PATIENT  INFORMATION [TEST] */ 
    CREATE TABLE CASES 
    (ID INTEGER AUTO_INCREMENT,
    ILL_ID INT ,
    foreign key (ILL_ID) references ILLNESES(ID),
    PATIENT_ID INTEGER,
    foreign key (PATIENT_ID) references PATIENT(id),
    PATIENT_SESSION_ID INTEGER,
    foreign key (PATIENT_SESSION_ID) references PATIENT_SESSION(ID),
    DATEof DATE NOT NULL,
    NOTES VARCHAR(500) NOT NULL,
    PRIMARY KEY(ID)
    );


      /* Designed By Rawand F. 
      LAST_UPDATE: 17th May 2018 :0028A
      */
